name: NAV Comparison

on:
  workflow_dispatch:    # run manually from Actions tab

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NAV comparison
        run: |
          python nav_compare.py

      - name: Upload NAV comparison result
        uses: actions/upload-artifact@v4
        with:
          name: nav-comparison
          path: NAV_Comparison_Result.xlsx
